# Fichier: ~/.dbt/profiles.yml (Ceci est le fichier de configuration de CONNEXION)

bigquery_client_project: 
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth # Utilisera votre authentification utilisateur sur le PC du client
      project: dbt-bq-training-473915 # lv-gcp-dcx-dev-dp-lake-ww L'ID de votre projet
      dataset: linkedin_company_pages #lv_bqd_dev_dp_linkedinpages_service  Le dataset où dbt va écrire les tables (staging/marts)
      threads: 4
      location: EU # Par défaut, nous supposons la région EU