{{
    config(
        materialized='incremental',
        schema='_MART',
        unique_key=['day', 'dimension_id', 'dimension', 'organization_id'],
        cluster_by=['day', 'organization_id', 'dimension'],
        incremental_strategy='merge',
        on_schema_change='fail',
        merge_update_columns=[
            'dimension_name',
            'geo_country_name',
            'continent',
            'Zone_LV',
            'Region_LV',
            'country_LV',
            'all_desktop_page_views',
            'all_mobile_page_views',
            'all_page_views',
            'about_page_views',
            'careers_page_views',
            'products_page_views',
            'jobs_page_views',
            'people_page_views',
            'overview_page_views',
            'life_at_page_views',
            'insights_page_views',
            'mobile_careers_page_views',
            'mobile_overview_page_views',
            'mobile_jobs_page_views',
            'mobile_life_at_page_views',
            'mobile_insights_page_views',
            'mobile_products_page_views',
            'mobile_about_page_views',
            'mobile_people_page_views',
            'desktop_insights_page_views',
            'desktop_careers_page_views',
            'desktop_life_at_page_views',
            'desktop_jobs_page_views',
            'desktop_people_page_views',
            'desktop_about_page_views',
            'desktop_overview_page_views',
            'desktop_products_page_views',
            '_fivetran_id',
            '_fivetran_synced'
        ]
    )
}}

WITH source_data AS (
    SELECT
        day,
        dimension_id,
        dimension,
        dimension_name,
        geo_country_name,
        continent,
        Zone_LV,
        Region_LV,
        country_LV,
        all_desktop_page_views,
        all_mobile_page_views,
        all_page_views,
        about_page_views,
        careers_page_views,
        products_page_views,
        jobs_page_views,
        people_page_views,
        overview_page_views,
        life_at_page_views,
        insights_page_views,
        mobile_careers_page_views,
        mobile_overview_page_views,
        mobile_jobs_page_views,
        mobile_life_at_page_views,
        mobile_insights_page_views,
        mobile_products_page_views,
        mobile_about_page_views,
        mobile_people_page_views,
        desktop_insights_page_views,
        desktop_careers_page_views,
        desktop_life_at_page_views,
        desktop_jobs_page_views,
        desktop_people_page_views,
        desktop_about_page_views,
        desktop_overview_page_views,
        desktop_products_page_views,
        _fivetran_id,
        _fivetran_synced,
        organization_id
    FROM {{ ref('mrt_pages_daily') }}
)

SELECT
    day,
    dimension_id,
    dimension,
    dimension_name,
    geo_country_name,
    continent,
    Zone_LV,
    Region_LV,
    country_LV,
    all_desktop_page_views,
    all_mobile_page_views,
    all_page_views,
    about_page_views,
    careers_page_views,
    products_page_views,
    jobs_page_views,
    people_page_views,
    overview_page_views,
    life_at_page_views,
    insights_page_views,
    mobile_careers_page_views,
    mobile_overview_page_views,
    mobile_jobs_page_views,
    mobile_life_at_page_views,
    mobile_insights_page_views,
    mobile_products_page_views,
    mobile_about_page_views,
    mobile_people_page_views,
    desktop_insights_page_views,
    desktop_careers_page_views,
    desktop_life_at_page_views,
    desktop_jobs_page_views,
    desktop_people_page_views,
    desktop_about_page_views,
    desktop_overview_page_views,
    desktop_products_page_views,
    _fivetran_id,
    _fivetran_synced,
    organization_id
FROM source_data
{% if is_incremental() %}
WHERE day >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)

MERGE INTO {{ this }} AS target
USING (
    SELECT
        day,
        dimension_id,
        dimension,
        dimension_name,
        geo_country_name,
        continent,
        Zone_LV,
        Region_LV,
        country_LV,
        all_desktop_page_views,
        all_mobile_page_views,
        all_page_views,
        about_page_views,
        careers_page_views,
        products_page_views,
        jobs_page_views,
        people_page_views,
        overview_page_views,
        life_at_page_views,
        insights_page_views,
        mobile_careers_page_views,
        mobile_overview_page_views,
        mobile_jobs_page_views,
        mobile_life_at_page_views,
        mobile_insights_page_views,
        mobile_products_page_views,
        mobile_about_page_views,
        mobile_people_page_views,
        desktop_insights_page_views,
        desktop_careers_page_views,
        desktop_life_at_page_views,
        desktop_jobs_page_views,
        desktop_people_page_views,
        desktop_about_page_views,
        desktop_overview_page_views,
        desktop_products_page_views,
        _fivetran_id,
        _fivetran_synced,
        organization_id
    FROM source_data
    WHERE day >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)
) AS source
ON target.day = source.day
   AND target.dimension_id = source.dimension_id
   AND target.dimension = source.dimension
   AND target.organization_id = source.organization_id
WHEN MATCHED AND source._fivetran_synced > target._fivetran_synced THEN
    UPDATE SET
        target.dimension_name = source.dimension_name,
        target.geo_country_name = source.geo_country_name,
        target.continent = source.continent,
        target.Zone_LV = source.Zone_LV,
        target.Region_LV = source.Region_LV,
        target.country_LV = source.country_LV,
        target.all_desktop_page_views = source.all_desktop_page_views,
        target.all_mobile_page_views = source.all_mobile_page_views,
        target.all_page_views = source.all_page_views,
        target.about_page_views = source.about_page_views,
        target.careers_page_views = source.careers_page_views,
        target.products_page_views = source.products_page_views,
        target.jobs_page_views = source.jobs_page_views,
        target.people_page_views = source.people_page_views,
        target.overview_page_views = source.overview_page_views,
        target.life_at_page_views = source.life_at_page_views,
        target.insights_page_views = source.insights_page_views,
        target.mobile_careers_page_views = source.mobile_careers_page_views,
        target.mobile_overview_page_views = source.mobile_overview_page_views,
        target.mobile_jobs_page_views = source.mobile_jobs_page_views,
        target.mobile_life_at_page_views = source.mobile_life_at_page_views,
        target.mobile_insights_page_views = source.mobile_insights_page_views,
        target.mobile_products_page_views = source.mobile_products_page_views,
        target.mobile_about_page_views = source.mobile_about_page_views,
        target.mobile_people_page_views = source.mobile_people_page_views,
        target.desktop_insights_page_views = source.desktop_insights_page_views,
        target.desktop_careers_page_views = source.desktop_careers_page_views,
        target.desktop_life_at_page_views = source.desktop_life_at_page_views,
        target.desktop_jobs_page_views = source.desktop_jobs_page_views,
        target.desktop_people_page_views = source.desktop_people_page_views,
        target.desktop_about_page_views = source.desktop_about_page_views,
        target.desktop_overview_page_views = source.desktop_overview_page_views,
        target.desktop_products_page_views = source.desktop_products_page_views,
        target._fivetran_id = source._fivetran_id,
        target._fivetran_synced = source._fivetran_synced
WHEN NOT MATCHED THEN
    INSERT (
        day,
        dimension_id,
        dimension,
        dimension_name,
        geo_country_name,
        continent,
        Zone_LV,
        Region_LV,
        country_LV,
        all_desktop_page_views,
        all_mobile_page_views,
        all_page_views,
        about_page_views,
        careers_page_views,
        products_page_views,
        jobs_page_views,
        people_page_views,
        overview_page_views,
        life_at_page_views,
        insights_page_views,
        mobile_careers_page_views,
        mobile_overview_page_views,
        mobile_jobs_page_views,
        mobile_life_at_page_views,
        mobile_insights_page_views,
        mobile_products_page_views,
        mobile_about_page_views,
        mobile_people_page_views,
        desktop_insights_page_views,
        desktop_careers_page_views,
        desktop_life_at_page_views,
        desktop_jobs_page_views,
        desktop_people_page_views,
        desktop_about_page_views,
        desktop_overview_page_views,
        desktop_products_page_views,
        _fivetran_id,
        _fivetran_synced,
        organization_id
    )
    VALUES (
        source.day,
        source.dimension_id,
        source.dimension,
        source.dimension_name,
        source.geo_country_name,
        source.continent,
        source.Zone_LV,
        source.Region_LV,
        source.country_LV,
        source.all_desktop_page_views,
        source.all_mobile_page_views,
        source.all_page_views,
        source.about_page_views,
        source.careers_page_views,
        source.products_page_views,
        source.jobs_page_views,
        source.people_page_views,
        source.overview_page_views,
        source.life_at_page_views,
        source.insights_page_views,
        source.mobile_careers_page_views,
        source.mobile_overview_page_views,
        source.mobile_jobs_page_views,
        source.mobile_life_at_page_views,
        source.mobile_insights_page_views,
        source.mobile_products_page_views,
        source.mobile_about_page_views,
        source.mobile_people_page_views,
        source.desktop_insights_page_views,
        source.desktop_careers_page_views,
        source.desktop_life_at_page_views,
        source.desktop_jobs_page_views,
        source.desktop_people_page_views,
        source.desktop_about_page_views,
        source.desktop_overview_page_views,
        source.desktop_products_page_views,
        source._fivetran_id,
        source._fivetran_synced,
        source.organization_id
    )
{% endif %}